title:              Cagiti
email:              cagiti@github.com
description:        A Blog for all things bloggy.
author:             Cai Cooper

# Social Profiles
github_username:    cagiti
linkedin_username:
markdown:           kramdown
theme: jekyll-theme-cayman
